"""Add initial tables

Revision ID: 2c93c0cd25b3
Revises: 
Create Date: 2026-01-03 15:12:18.336728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c93c0cd25b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('cadastrado_em', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('numero', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('agencia', sa.String(length=4), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('historico_id', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['historico_id'], ['transacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.Column('cadastrado_em', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conta_corrente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('limite', sa.Float(), nullable=True),
    sa.Column('limite_saque', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa_fisica',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nascimento', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id'),
    sa.UniqueConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoa_fisica')
    op.drop_table('conta_corrente')
    op.drop_table('transacao')
    op.drop_table('contas')
    op.drop_table('cliente')
    # ### end Alembic commands ###
