"""alterado nome de coluna de conta

Revision ID: 5a51e9ba71fc
Revises: 37b90d65cde4
Create Date: 2026-01-05 19:47:10.870924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a51e9ba71fc'
down_revision: Union[str, Sequence[str], None] = '37b90d65cde4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
