"""recriando banco do zero com novo formato atualizado

Revision ID: 7bc463103667
Revises: 
Create Date: 2026-01-04 10:40:19.111208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc463103667'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('cadastrado_em', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('numero', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('agencia', sa.String(length=4), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('historico_id', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['historico_id'], ['transacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.Column('cadastrado_em', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conta_corrente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('limite', sa.Float(), nullable=True),
    sa.Column('limite_saque', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conta_empresarial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('emprestimo', sa.Float(), nullable=True),
    sa.Column('emprestimo_limite', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa_fisica',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=2), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('pessoa_juridica',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=2), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoa_juridica')
    op.drop_table('pessoa_fisica')
    op.drop_table('conta_empresarial')
    op.drop_table('conta_corrente')
    op.drop_table('transacao')
    op.drop_table('conta')
    op.drop_table('cliente')
    # ### end Alembic commands ###
