"""Retirado NUMERO da conta por ser identico ao ID

Revision ID: 8fe1766ffcec
Revises: 5a51e9ba71fc
Create Date: 2026-01-06 17:06:36.344272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe1766ffcec'
down_revision: Union[str, Sequence[str], None] = '5a51e9ba71fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.drop_column('numero')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
