"""Retirado coluna SENHA da tabela CLIENTE

Revision ID: c20836193540
Revises: 15709af0f59c
Create Date: 2026-01-08 18:59:22.898795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20836193540'
down_revision: Union[str, Sequence[str], None] = '15709af0f59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
