"""Acrescimo de coluna de validao se saque ou deposito foi realizado com sucesso em TRANSACAO

Revision ID: cdc89d6bf386
Revises: 8fe1766ffcec
Create Date: 2026-01-06 20:35:01.391156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc89d6bf386'
down_revision: Union[str, Sequence[str], None] = '8fe1766ffcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('com_sucesso', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.drop_column('com_sucesso')

    # ### end Alembic commands ###
