"""deletando a coluna TIPO

Revision ID: f1753412f2d1
Revises: bad5cda5f447
Create Date: 2026-01-04 17:08:36.172533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1753412f2d1'
down_revision: Union[str, Sequence[str], None] = 'bad5cda5f447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoa_fisica', 'tipo')
    op.drop_column('pessoa_juridica', 'tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa_juridica', sa.Column('tipo', sa.VARCHAR(length=2), nullable=True))
    op.add_column('pessoa_fisica', sa.Column('tipo', sa.VARCHAR(length=2), nullable=True))
    # ### end Alembic commands ###
